from __future__ import annotations

from fastapi.responses import HTMLResponse


def control_panel_page() -> HTMLResponse:
    html = r'''<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Betano Live Analyzer · Panel</title>
<style>
:root{--bg:#0b1220;--panel:#111b2e;--panel2:#17233a;--text:#edf3ff;--muted:#9eacc4;--accent:#38bdf8;--ok:#34d399;--warn:#fbbf24;--danger:#fb7185;--line:#263653}
*{box-sizing:border-box}body{margin:0;font-family:Inter,Segoe UI,Arial,sans-serif;background:#f3f6fb;color:#172033}header{background:linear-gradient(135deg,#0b1220,#17233a);color:white;padding:24px 28px}header h1{margin:0 0 6px;font-size:28px}header p{margin:0;color:#b9c6da}.wrap{max-width:1500px;margin:auto;padding:20px}.nav{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}.nav a{background:white;border:1px solid #dce3ef;border-radius:10px;padding:10px 14px;text-decoration:none;color:#1b2940;font-weight:700}.nav a.primary{background:#17233a;color:white}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.card{background:white;border:1px solid #e1e7f0;border-radius:16px;padding:18px;box-shadow:0 5px 18px #1720330d}.wide{grid-column:1/-1}.card h2{margin:0 0 4px;font-size:19px}.desc{color:#68758a;font-size:13px;margin:0 0 15px}.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.field{display:flex;flex-direction:column;gap:5px}.field.full{grid-column:1/-1}label{font-size:12px;font-weight:800;color:#4d5a70}input,select,textarea{width:100%;border:1px solid #ccd6e5;border-radius:9px;padding:10px;font:inherit;background:#fff}textarea{min-height:90px;resize:vertical}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}button{border:0;border-radius:9px;padding:10px 14px;background:#17233a;color:white;font-weight:800;cursor:pointer}button.secondary{background:#e8edf5;color:#25324a}button.success{background:#0f8a62}button.warn{background:#b77900}button.danger{background:#b4233c}.result{margin-top:12px;background:#0b1220;color:#d9e6fb;border-radius:10px;padding:12px;min-height:48px;font:12px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace;white-space:pre-wrap;overflow:auto}.status{font-size:13px;font-weight:700;margin-top:8px}.pill{display:inline-block;border-radius:999px;padding:4px 8px;background:#eaf8f3;color:#08734f;font-size:11px;font-weight:800}.hint{font-size:12px;color:#69768a}.links{display:flex;gap:10px;flex-wrap:wrap}.links a{color:#1268a3;font-weight:700}@media(max-width:900px){.grid,.fields{grid-template-columns:1fr}.wide{grid-column:auto}}
</style></head>
<body>
<header><h1>⚽ Betano Live Analyzer · Centro de Pruebas</h1><p>Panel visual para alimentar datos, ejecutar análisis y verificar cada módulo sin usar Swagger.</p></header>
<div class="wrap">
<div class="nav"><a class="primary" href="/panel">🎛️ Panel</a><a href="/">📊 Dashboard</a><a href="/telegram-test">📨 Telegram</a><a href="/docs">📚 API / Docs</a></div>
<div class="grid">
<section class="card"><h2>🏟️ Crear partido</h2><p class="desc">Registra un evento para probar cuotas, picks y análisis.</p><div class="fields">
<div class="field"><label>Competición *</label><input id="competition" value="Liga de prueba"></div><div class="field"><label>External ID</label><input id="external_id" value="demo-001"></div>
<div class="field"><label>Equipo local *</label><input id="home_team" value="Liverpool"></div><div class="field"><label>Equipo visitante *</label><input id="away_team" value="Arsenal"></div>
<div class="field"><label>Kickoff *</label><input id="kickoff" type="datetime-local"></div><div class="field"><label>Estado</label><select id="match_status"><option>scheduled</option><option>live</option><option>in_play</option></select></div></div><div class="actions"><button onclick="createMatch()">CREAR PARTIDO</button></div><div id="matchResult" class="result">Esperando...</div></section>

<section class="card"><h2>👤 Crear tipster</h2><p class="desc">Registra la fuente que alimentará picks manuales o Telegram.</p><div class="fields"><div class="field"><label>Nombre *</label><input id="tipster_name" value="Tipster Demo"></div><div class="field"><label>Fuente</label><input id="tipster_source" value="Telegram"></div><div class="field"><label>País</label><input id="tipster_country" value="Perú"></div><div class="field"><label>Idioma</label><input id="tipster_language" value="es"></div></div><div class="actions"><button onclick="createTipster()">CREAR TIPSTER</button></div><div id="tipsterResult" class="result">Esperando...</div></section>

<section class="card"><h2>💹 Registrar cuota</h2><p class="desc">Introduce una cuota almacenada para alimentar Radar, CLV y Surebet.</p><div class="fields"><div class="field"><label>ID partido *</label><input id="odds_match_id" type="number" value="1"></div><div class="field"><label>Casa *</label><input id="odds_bookmaker" value="Betano"></div><div class="field"><label>Mercado *</label><input id="odds_market" value="total_goals"></div><div class="field"><label>Selección *</label><input id="odds_selection" value="Over 2.5"></div><div class="field"><label>Cuota *</label><input id="odds_value" type="number" step="0.01" value="1.85"></div><div class="field"><label>Línea</label><input id="odds_line" type="number" step="0.01" value="2.5"></div></div><div class="actions"><button onclick="createOdds()">GUARDAR CUOTA</button></div><div id="oddsResult" class="result">Esperando...</div></section>

<section class="card"><h2>🎯 Crear pick</h2><p class="desc">Permite probar el motor de picks y su versión conservadora.</p><div class="fields"><div class="field"><label>ID partido *</label><input id="pick_match_id" type="number" value="1"></div><div class="field"><label>ID tipster</label><input id="pick_tipster_id" type="number" value="1"></div><div class="field"><label>Mercado *</label><input id="pick_market" value="total_goals"></div><div class="field"><label>Selección *</label><input id="pick_selection" value="Over 2.5"></div><div class="field"><label>Cuota original</label><input id="pick_odds" type="number" step="0.01" value="1.85"></div><div class="field"><label>Probabilidad</label><input id="pick_probability" type="number" min="0" max="1" step="0.01" value="0.58"></div></div><div class="actions"><button onclick="createPick()">CREAR PICK</button><button class="secondary" onclick="previewConservative()">VER PREVISUALIZACIÓN CONSERVADORA</button></div><div id="pickResult" class="result">Esperando...</div></section>

<section class="card"><h2>💵 Registrar apuesta</h2><p class="desc">Registra una apuesta para que el módulo de rendimiento pueda mostrar resultados.</p><div class="fields"><div class="field"><label>ID partido *</label><input id="bet_match_id" type="number" value="1"></div><div class="field"><label>ID pick</label><input id="bet_pick_id" type="number" value="1"></div><div class="field"><label>Selección *</label><input id="bet_selection" value="Over 2.5"></div><div class="field"><label>Cuota *</label><input id="bet_odds" type="number" step="0.01" value="1.85"></div><div class="field"><label>Stake *</label><input id="bet_stake" type="number" step="0.01" value="10"></div><div class="field"><label>Resultado</label><select id="bet_result"><option>pending</option><option>won</option><option>lost</option><option>push</option><option>cashout</option></select></div><div class="field full"><label>Fecha/hora colocación *</label><input id="bet_placed_at" type="datetime-local"></div></div><div class="actions"><button onclick="createBet()">REGISTRAR APUESTA</button></div><div id="betResult" class="result">Esperando...</div></section>

<section class="card"><h2>🔄 Sincronizar cuotas</h2><p class="desc">Ejecuta la sincronización configurada. Puede requerir credenciales de proveedores.</p><div class="fields"><div class="field"><label>Casas</label><input id="sync_books" value="Betano"></div><div class="field"><label>Límite por liga</label><input id="sync_limit" type="number" value="20"></div></div><div class="actions"><button class="success" onclick="syncOdds(false)">SINCRONIZAR PRE-PARTIDO</button><button class="danger" onclick="syncOdds(true)">🔴 SINCRONIZAR LIVE</button></div><div id="syncResult" class="result">No se ha ejecutado una sincronización.</div></section>

<section class="card wide"><h2>📡 Módulos de análisis</h2><p class="desc">Ejecuta los radares y consultas principales y observa el JSON real que devuelve el backend.</p><div class="actions"><button onclick="getJson('/api/v1/opportunities?limit=20','analysisResult')">Radar</button><button onclick="getJson('/api/v1/value-radar?limit=20','analysisResult')">Value Radar</button><button onclick="getJson('/api/v1/master-radar?limit=20','analysisResult')">Master Radar</button><button onclick="getJson('/api/v1/final-selection?limit=10','analysisResult')">Selección final</button><button onclick="getJson('/api/v1/movements','analysisResult')">Movimientos</button><button onclick="getJson('/api/v1/clv/summary?period=todos','analysisResult')">CLV</button><button onclick="getJson('/api/v1/backtest/report?period=todos','analysisResult')">Backtest</button><button onclick="getJson('/api/v1/providers','analysisResult')">Proveedores</button></div><div id="analysisResult" class="result">Selecciona un módulo.</div></section>

<section class="card"><h2>📨 Telegram</h2><p class="desc">Acceso rápido a la prueba de señales y estado seguro de configuración.</p><div class="actions"><a class="pill" href="/telegram-test">ABRIR FORMULARIO TELEGRAM</a><button class="secondary" onclick="getJson('/api/v1/telegram/config','telegramStatus')">COMPROBAR CONFIGURACIÓN</button></div><div id="telegramStatus" class="result">Sin comprobar.</div></section>

<section class="card"><h2>🩺 Salud del sistema</h2><p class="desc">Comprueba rápidamente que FastAPI y la aplicación responden.</p><div class="actions"><button class="success" onclick="getJson('/api/v1/health','healthResult')">HEALTH</button><button class="secondary" onclick="getJson('/health','healthResult')">HEALTH RAÍZ</button></div><div id="healthResult" class="result">Sin comprobar.</div></section>
</div>
</div>
<script>
const $=id=>document.getElementById(id);
const val=id=>$(id).value;
function show(id,data){$(id).textContent=typeof data==='string'?data:JSON.stringify(data,null,2)}
async function request(url,options={}){const r=await fetch(url,options);let d;try{d=await r.json()}catch{d=await r.text()}if(!r.ok)throw new Error(typeof d==='object'?(d.detail||JSON.stringify(d)):d);return d}
async function getJson(url,id){show(id,'Cargando...');try{show(id,await request(url))}catch(e){show(id,'ERROR: '+e.message)}}
function isoLocal(id){const v=val(id);return v?new Date(v).toISOString():new Date().toISOString()}
async function createMatch(){try{show('matchResult',await request('/api/v1/matches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({external_id:val('external_id')||null,competition:val('competition'),home_team:val('home_team'),away_team:val('away_team'),kickoff:isoLocal('kickoff'),status:val('match_status')})}))}catch(e){show('matchResult','ERROR: '+e.message)}}
async function createTipster(){try{show('tipsterResult',await request('/api/v1/tipsters',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:val('tipster_name'),source:val('tipster_source')||null,country:val('tipster_country')||null,language:val('tipster_language')||null,active:true})}))}catch(e){show('tipsterResult','ERROR: '+e.message)}}
async function createOdds(){try{show('oddsResult',await request('/api/v1/odds',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({match_id:Number(val('odds_match_id')),bookmaker:val('odds_bookmaker'),market:val('odds_market'),selection:val('odds_selection'),odds:Number(val('odds_value')),line:val('odds_line')?Number(val('odds_line')):null})}))}catch(e){show('oddsResult','ERROR: '+e.message)}}
async function previewConservative(){try{const u='/api/v1/conservative-preview?market='+encodeURIComponent(val('pick_market'))+'&selection='+encodeURIComponent(val('pick_selection'));show('pickResult',await request(u))}catch(e){show('pickResult','ERROR: '+e.message)}}
async function createPick(){try{const b={match_id:Number(val('pick_match_id')),tipster_id:val('pick_tipster_id')?Number(val('pick_tipster_id')):null,original_market:val('pick_market'),original_selection:val('pick_selection'),original_odds:val('pick_odds')?Number(val('pick_odds')):null,confidence:null,probability:val('pick_probability')?Number(val('pick_probability')):null,probability_source:'manual'};show('pickResult',await request('/api/v1/picks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}))}catch(e){show('pickResult','ERROR: '+e.message)}}
async function createBet(){try{const b={match_id:Number(val('bet_match_id')),pick_id:val('bet_pick_id')?Number(val('bet_pick_id')):null,selection:val('bet_selection'),odds:Number(val('bet_odds')),stake:Number(val('bet_stake')),result:val('bet_result'),cashout:null,placed_at:isoLocal('bet_placed_at')};show('betResult',await request('/api/v1/bets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}))}catch(e){show('betResult','ERROR: '+e.message)}}
async function syncOdds(live){show('syncResult','Sincronizando...');try{const u='/api/v1/sync/odds?bookmakers='+encodeURIComponent(val('sync_books'))+'&include_live='+live+'&limit_per_league='+encodeURIComponent(val('sync_limit'));show('syncResult',await request(u,{method:'POST'}))}catch(e){show('syncResult','ERROR: '+e.message)}}
const now=new Date();$('bet_placed_at').value=new Date(now-now.getTimezoneOffset()*60000).toISOString().slice(0,16);$('kickoff').value=new Date(now.getTime()+86400000-now.getTimezoneOffset()*60000).toISOString().slice(0,16);
</script></body></html>'''
    return HTMLResponse(html)
