from __future__ import annotations

from fastapi.responses import HTMLResponse


def provider_accounts_page() -> HTMLResponse:
    html = r'''<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Conexión API · ANALISYS BETSTOTAL</title>
<style>
body{font-family:Segoe UI,Arial,sans-serif;background:#f3f6fb;color:#172033;margin:0}header{background:#111b2e;color:#fff;padding:24px}main{max-width:1200px;margin:auto;padding:20px}.card{background:#fff;border:1px solid #dde5f0;border-radius:16px;padding:20px;margin-bottom:16px;box-shadow:0 5px 18px #1720330d}.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.field{display:flex;flex-direction:column;gap:5px}.field.full{grid-column:1/-1}label{font-size:12px;font-weight:800;color:#4d5a70}input,select{width:100%;border:1px solid #ccd6e5;border-radius:9px;padding:10px;font:inherit;box-sizing:border-box}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}button{border:0;border-radius:9px;padding:10px 14px;background:#17233a;color:#fff;font-weight:800;cursor:pointer}button.success{background:#0f8a62}button.analysis{background:#2563eb;font-size:15px;padding:12px 18px}button:disabled{opacity:.6;cursor:wait}.result{background:#0b1220;color:#d9e6fb;border-radius:10px;padding:14px;white-space:pre-wrap;font:12px/1.5 monospace;min-height:35px;margin-top:12px}.account{border:1px solid #d9e2ef;border-radius:12px;padding:14px;margin-top:10px}.active{border-color:#0f8a62;background:#f0fbf7}.pill{display:inline-block;border-radius:999px;padding:4px 8px;background:#eaf8f3;color:#08734f;font-size:11px;font-weight:800}.hint{color:#68758a;font-size:13px;line-height:1.5}.warn{background:#fff8e6;border:1px solid #f3d27a;padding:12px;border-radius:10px;font-size:13px}.report{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;margin-top:12px}.metric{background:#eef4fb;border-radius:12px;padding:12px}.metric b{display:block;font-size:24px}.metric span{font-size:11px;color:#526176;font-weight:700}.report-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:14px}.report-list>div{background:#f8fafc;border:1px solid #e5eaf1;border-radius:12px;padding:12px;max-height:240px;overflow:auto}.report-list h3{font-size:13px;margin:0 0 8px}.report-list ul{margin:0;padding-left:18px;font-size:12px;line-height:1.7}@media(max-width:850px){.report{grid-template-columns:repeat(2,1fr)}.report-list{grid-template-columns:1fr}}@media(max-width:600px){.fields,.report{grid-template-columns:1fr}.field.full{grid-column:auto}}
</style></head>
<body><header><h1>🔐 CONEXIÓN API</h1><p>Conecta OddsPapi una sola vez y deja la cuenta activa para el Analyzer.</p></header>
<main>
<div class="card"><h2>🔐 Conectar OddsPapi</h2><p class="hint">El correo identifica la cuenta. Usa únicamente la <strong>API Key</strong> de OddsPapi; no introduzcas aquí tu contraseña.</p><div class="warn">⚠️ La conexión primero valida la API Key y solo si es válida la guarda y la activa. La clave nunca se muestra completa en pantalla.</div><div class="fields" style="margin-top:12px"><div class="field"><label>Proveedor</label><select id="provider"><option value="oddspapi">OddsPapi</option></select></div><div class="field"><label>Nombre de la cuenta</label><input id="label" placeholder="Ej. OddsPapi Perú"></div><div class="field"><label>Correo de la cuenta</label><input id="email" type="email" placeholder="tu-correo@..." autocomplete="off"></div><div class="field"><label>API Key *</label><input id="api_key" type="password" placeholder="Pega aquí tu API Key" autocomplete="off"></div></div><div class="actions"><button class="success" id="connectBtn" onclick="connectAccount()">🔗 CONECTAR Y ACTIVAR</button><a href="/">🏠 Panel principal</a></div><div id="result" class="result">Introduce tus datos y pulsa CONECTAR Y ACTIVAR.</div></div>
<div class="card" id="full-analysis"><h2>🔎 ANÁLISIS INTEGRAL DE INFORMACIÓN</h2><p class="hint">Opcional: estudia qué información permite consultar la cuenta sin pedir cuotas masivas. Se controla el presupuesto de solicitudes.</p><div class="actions"><button class="analysis" id="analyzeAll" onclick="analyzeAll()">🧠 ANALIZAR TODO</button></div><div id="analysisStatus" class="result">Pulsa ANALIZAR TODO para generar el informe.</div><div id="reportMetrics" class="report"></div><div id="reportLists" class="report-list"></div></div>
<div class="card"><h2>📊 ESCÁNER CONTROLADO</h2><p class="hint">Catálogo = deportes, casas y mercados. Profundo = además recorre torneos y eventos de las próximas 48 horas, siempre dentro del presupuesto indicado.</p><div class="actions"><button class="success" onclick="scan(false)">📊 ESCANEAR CATÁLOGO</button><button onclick="scan(true)">🌎 ESCANEO PROFUNDO CONTROLADO</button></div><div id="scanResult" class="result">Todavía no se ha ejecutado el escáner.</div></div>
<div class="card"><h2>📊 Cuenta activa</h2><p class="hint">La cuenta activa queda enlazada al Analyzer y permanece disponible al navegar entre las secciones.</p><div id="accounts">Cargando...</div></div>
</main>
<script>
const $=id=>document.getElementById(id);const val=id=>$(id).value;
async function req(url,opts={}){const r=await fetch(url,opts);let d;try{d=await r.json()}catch{d=await r.text()}if(!r.ok)throw new Error(typeof d==='object'?(d.detail||JSON.stringify(d)):d);return d}
function show(d,id='result'){ $(id).textContent=typeof d==='string'?d:JSON.stringify(d,null,2)}
async function connectAccount(){const b=$('connectBtn');if(!val('api_key').trim()){show('Escribe la API Key primero.');return}b.disabled=true;b.textContent='⏳ VALIDANDO Y CONECTANDO...';show('Validando API Key con OddsPapi. No se guardará si falla la validación...');try{const d=await req('/api/v1/provider-accounts/connect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:val('provider'),label:val('label'),email:val('email'),api_key:val('api_key')})});$('api_key').value='';show({connected:d.connected,account:d.account,plan:d.plan,subscription_status:d.subscription_status,usage:d.usage,valid_from:d.valid_from,valid_until:d.valid_until});await loadAccounts();setTimeout(()=>{window.location.href='/';},900)}catch(e){show('❌ NO SE PUDO CONECTAR: '+e.message)}finally{b.disabled=false;b.textContent='🔗 CONECTAR Y ACTIVAR'}}
function metric(label,value){return `<div class="metric"><b>${value??0}</b><span>${label}</span></div>`}
function listBlock(title,items){const rows=Array.isArray(items)?items:Object.entries(items||{}).sort((a,b)=>Number(b[1])-Number(a[1])).map(([k,v])=>`${k}: ${v}`);return `<div><h3>${title}</h3><ul>${rows.slice(0,100).map(x=>`<li>${escapeHtml(String(x))}</li>`).join('')||'<li>Sin datos disponibles</li>'}</ul></div>`}
async function analyzeAll(){const b=$('analyzeAll');b.disabled=true;b.textContent='⏳ ANALIZANDO...';$('analysisStatus').textContent='Consultando catálogo y, dentro del presupuesto, torneos y eventos de las próximas 48 horas. No se solicitan cuotas masivas.';$('reportMetrics').innerHTML='';$('reportLists').innerHTML='';try{const d=await req('/api/v1/oddspapi/scan?deep=true&max_requests=40',{method:'POST'});const s=d.summary||{},c=d.capabilities||{};$('analysisStatus').textContent=`✅ ANÁLISIS COMPLETO TERMINADO · ${d.scan?.requests_used_by_scanner||0}/${d.scan?.max_requests||40} solicitudes medidas · ${d.scan?.stopped_reason||'recorrido finalizado'}`;$('reportMetrics').innerHTML=[['🎮 Tipos de juego / deportes',s.sports],['🏟️ Eventos 48h',s.fixtures_48h],['🏆 Ligas / torneos',s.tournaments],['👥 Equipos / participantes',s.participants_48h],['🏦 Casas de apuesta',s.bookmakers],['🌎 Países de ligas',s.countries],['📋 Mercados',s.markets],['🎯 Resultados de mercados',s.market_outcomes],['🟢 Eventos LIVE',s.live_fixtures_48h],['📅 Eventos PRE',s.upcoming_fixtures_48h],['🌐 Países de casas',s.bookmaker_countries],['🧩 Tipos de mercado',s.market_types]].map(x=>metric(x[0],x[1])).join('');$('reportLists').innerHTML=listBlock('🌎 Países / regiones de ligas',d.countries)+listBlock('🏦 Casas por país',d.bookmaker_countries)+listBlock('🎮 Ligas por deporte',d.tournament_counts_by_sport)+listBlock('📋 Mercados y cantidad de resultados',d.market_outcomes_by_market)+listBlock('👥 Equipos detectados (muestra)',d.participants_sample)+listBlock('⚙️ Capacidades de la cuenta',[`LIVE odds: ${c.live_odds?'SÍ':'NO'}`,`Player props: ${c.player_props?'SÍ':'NO'}`,`WebSocket: ${c.websocket?'SÍ':'NO'}`,`Cuotas históricas: ${c.historical_odds?'SÍ':'NO'}`])+listBlock('⏱️ Ventana y control',[`Ventana: ${d.scan?.window_hours||0} horas`,`Solicitudes usadas: ${d.scan?.requests_used_by_scanner||0}`,`Presupuesto: ${d.scan?.max_requests||40}`]);}catch(e){$('analysisStatus').textContent='❌ ERROR DEL ANÁLISIS: '+e.message}finally{b.disabled=false;b.textContent='🧠 ANALIZAR TODO'}}
async function scan(deep){$('scanResult').textContent='Consultando OddsPapi...';try{const d=await req('/api/v1/oddspapi/scan?deep='+deep+'&max_requests='+(deep?40:3),{method:'POST'});show(d,'scanResult')}catch(e){show('ERROR DEL ESCÁNER: '+e.message,'scanResult')}}
async function loadAccounts(){try{const d=await req('/api/v1/provider-accounts');const rows=d.accounts||[];$('accounts').innerHTML=rows.length?rows.map(a=>`<div class="account ${a.active?'active':''}"><strong>${escapeHtml(a.label||a.id)}</strong> ${a.active?'<span class="pill">🟢 ACTIVA</span>':'<span>⚪ Inactiva</span>'}<div>Proveedor: ${escapeHtml(a.provider)} · Correo: ${escapeHtml(a.email||'no indicado')}</div><div>API Key: ${escapeHtml(a.api_key_masked)}</div></div>`).join(''):'No hay cuentas conectadas.'}catch(e){$('accounts').textContent='ERROR: '+e.message}}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
loadAccounts();
</script></body></html>'''
    return HTMLResponse(html)
