from __future__ import annotations

from fastapi.responses import HTMLResponse


def provider_accounts_page() -> HTMLResponse:
    html = r'''<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Conexión API · ANALISYS BETSTOTAL</title>
<style>
body{font-family:Segoe UI,Arial,sans-serif;background:#f3f6fb;color:#172033;margin:0}header{background:#111b2e;color:#fff;padding:24px}main{max-width:1200px;margin:auto;padding:20px}.card{background:#fff;border:1px solid #dde5f0;border-radius:16px;padding:20px;margin-bottom:16px;box-shadow:0 5px 18px #1720330d}.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.field{display:flex;flex-direction:column;gap:5px}.field.full{grid-column:1/-1}label{font-size:12px;font-weight:800;color:#4d5a70}input,select{width:100%;border:1px solid #ccd6e5;border-radius:9px;padding:10px;font:inherit;box-sizing:border-box}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}button{border:0;border-radius:9px;padding:10px 14px;background:#17233a;color:#fff;font-weight:800;cursor:pointer}button.success{background:#0f8a62}button.secondary{background:#475569}button.danger{background:#a51d2d}button:disabled{opacity:.6;cursor:wait}.result{background:#0b1220;color:#d9e6fb;border-radius:10px;padding:14px;white-space:pre-wrap;font:12px/1.5 monospace;min-height:35px;margin-top:12px}.provider{border:1px solid #d9e2ef;border-radius:12px;padding:14px;margin-top:10px}.provider.active{border-color:#0f8a62;background:#f0fbf7}.pill{display:inline-block;border-radius:999px;padding:4px 8px;background:#eaf8f3;color:#08734f;font-size:11px;font-weight:800}.hint{color:#68758a;font-size:13px;line-height:1.5}.warn{background:#fff8e6;border:1px solid #f3d27a;padding:12px;border-radius:10px;font-size:13px}.ok{background:#ecfdf5;border:1px solid #b7ebd4;padding:12px;border-radius:10px}.report{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;margin-top:12px}.metric{background:#eef4fb;border-radius:12px;padding:12px}.metric b{display:block;font-size:24px}.metric span{font-size:11px;color:#526176;font-weight:700}.config{display:none;border-top:1px solid #e5eaf1;margin-top:16px;padding-top:16px}.config.show{display:block}.connection-grid{display:grid;grid-template-columns:2fr 1fr;gap:16px}.status-card{background:#f8fafc;border:1px solid #e5eaf1;border-radius:12px;padding:14px}.status-dot{font-weight:900}.connected{color:#08734f}.disconnected{color:#a51d2d}@media(max-width:850px){.connection-grid{grid-template-columns:1fr}.report{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.fields,.report{grid-template-columns:1fr}.field.full{grid-column:auto}}
</style></head>
<body><header><h1>🔐 CONEXIÓN API</h1><p>Un solo lugar para conectar, seleccionar y administrar proveedores de cuotas.</p></header>
<main>
<div class="card"><div class="connection-grid"><div><h2>🔑 Conexión de la sesión</h2><p class="hint">La API Key se solicita al iniciar el aplicativo. Se mantiene únicamente en memoria mientras el aplicativo está abierto y se borra al cerrarlo.</p><div class="warn">⚠️ La API Key <strong>no se guarda en archivos</strong>. Al volver a abrir el aplicativo tendrás que introducirla nuevamente.</div><div class="fields" style="margin-top:12px"><div class="field"><label>Proveedor</label><select id="provider" onchange="providerChanged()"></select></div><div class="field"><label>Nombre</label><input id="label" value="LUCIANO" placeholder="Nombre del proveedor"></div><div class="field"><label>Correo</label><input id="email" type="email" value="wsluciano@hotmail.com" autocomplete="off"></div><div class="field"><label>API Key *</label><input id="api_key" type="password" placeholder="Pega aquí tu API Key" autocomplete="off"></div></div><div class="actions"><button class="success" id="connectBtn" onclick="connectAccount()">🔗 CONECTAR Y ACTIVAR</button><a href="/">🏠 Panel principal</a></div><div id="result" class="result">Introduce la Key y pulsa CONECTAR Y ACTIVAR.</div></div><div class="status-card"><h3>Estado actual</h3><div id="currentStatus">Cargando...</div><div class="actions"><button class="secondary" onclick="toggleConfig()">⚙️ CONFIGURAR PROVEEDORES</button></div></div></div></div>

<div class="card config" id="config"><h2>⚙️ Configurar proveedores de cuotas</h2><p class="hint">Aquí puedes registrar los proveedores que quieras. Se guarda la configuración del proveedor, pero sus claves permanecen solo en la sesión.</p><div class="fields"><div class="field"><label>Proveedor / identificador</label><input id="newProvider" placeholder="Ej. OddsPapi"></div><div class="field"><label>Nombre visible</label><input id="newLabel" placeholder="Ej. OddsPapi principal"></div><div class="field"><label>URL base</label><input id="newBase" placeholder="https://api.ejemplo.com/v1"></div><div class="field"><label>Endpoint de prueba</label><input id="newTestPath" value="/account" placeholder="/account"></div><div class="field"><label>Autenticación</label><select id="newAuthLocation"><option value="query">Query parameter</option><option value="header">Header</option></select></div><div class="field"><label>Nombre de la credencial</label><input id="newAuthName" value="apiKey" placeholder="apiKey / Authorization / X-API-Key"></div></div><div class="actions"><button class="success" onclick="saveProvider()">➕ AGREGAR / ACTUALIZAR PROVEEDOR</button></div><div id="providerResult" class="result">Registra un proveedor para que aparezca en el selector.</div><div id="providers">Cargando proveedores...</div></div>

<div class="card"><h2>📊 Proveedor seleccionado</h2><div id="selectedProvider">Cargando...</div></div>
<div class="card"><h2>🔎 Análisis de información de OddsPapi</h2><p class="hint">Solo disponible cuando OddsPapi es el proveedor conectado. El escaneo respeta el presupuesto de solicitudes.</p><div class="actions"><button onclick="analyzeAll()">🧠 ANALIZAR TODO</button></div><div id="analysisStatus" class="result">Sin ejecutar.</div><div id="reportMetrics" class="report"></div></div>
</main>
<script>
const $=id=>document.getElementById(id);const val=id=>$(id).value;
let rows=[];
async function req(url,opts={}){const r=await fetch(url,opts);let d;try{d=await r.json()}catch{d=await r.text()}if(!r.ok)throw new Error(typeof d==='object'?(d.detail||JSON.stringify(d)):d);return d}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toggleConfig(){$('config').classList.toggle('show')}
function providerChanged(){const p=rows.find(x=>x.id===val('provider'));if(!p)return;$('label').value=p.label||p.provider;$('email').value=p.email||'wsluciano@hotmail.com';$('api_key').value=''}
async function load(){try{const d=await req('/api/v1/provider-accounts');rows=d.accounts||[];const opts=rows.length?rows.map(p=>`<option value="${esc(p.id)}">${esc(p.label||p.provider)} · ${esc(p.provider)}</option>`).join(''):'<option value="">OddsPapi</option>';$('provider').innerHTML=opts;const active=rows.find(p=>p.active);$('currentStatus').innerHTML=active?`<div class="status-dot connected">🟢 CONECTADO · ${esc(active.label)}</div><div>Proveedor: ${esc(active.provider)}</div>`:'<div class="status-dot disconnected">🔴 NO CONECTADO</div><div>Introduce una API Key para iniciar.</div>';if(active){$('provider').value=active.id;providerChanged();$('selectedProvider').innerHTML=`<b>${esc(active.label)}</b> · ${esc(active.provider)}<br>Estado: 🟢 Activo<br>Key: ${esc(active.api_key_masked)}`;}else{$('selectedProvider').textContent='Ningún proveedor conectado en esta sesión.'}renderProviders();}catch(e){$('currentStatus').textContent='ERROR: '+e.message}}
function renderProviders(){$('providers').innerHTML=rows.length?rows.map(p=>`<div class="provider ${p.active?'active':''}"><b>${esc(p.label||p.provider)}</b> ${p.active?'<span class="pill">🟢 ACTIVO</span>':'<span>⚪ Registrado</span>'}<div>Proveedor: ${esc(p.provider)} · URL: ${esc(p.base_url)}</div><div>Key de esta sesión: ${p.connected?esc(p.api_key_masked):'No cargada'}</div><div class="actions">${p.connected&&!p.active?`<button onclick="activate('${esc(p.id)}')">USAR ESTE PROVEEDOR</button>`:''}<button class="danger" onclick="removeProvider('${esc(p.id)}')">QUITAR</button></div></div>`).join(''):'No hay proveedores registrados todavía.'}
async function connectAccount(){const b=$('connectBtn');if(!val('api_key').trim()){show('Escribe la API Key primero.');return}const p=rows.find(x=>x.id===val('provider'));const provider=p?.provider||'oddspapi';const base=p?.base_url||'https://api.oddspapi.io/v4';const loc=p?.auth_location||'query';const auth=p?.auth_name||'apiKey';const test=p?.test_path||'/account';b.disabled=true;b.textContent='⏳ VALIDANDO...';show('Validando conexión. La clave solo quedará en memoria si la prueba es correcta.');try{const d=await req('/api/v1/provider-accounts/connect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,label:val('label'),email:val('email'),api_key:val('api_key'),account_id:p?.id||null,base_url:base,auth_location:loc,auth_name:auth,test_path:test})});$('api_key').value='';show({connected:d.connected,account:d.account,plan:d.plan,subscription_status:d.subscription_status,usage:d.usage});await load();setTimeout(()=>location.href='/',700)}catch(e){show('❌ NO SE PUDO CONECTAR: '+e.message)}finally{b.disabled=false;b.textContent='🔗 CONECTAR Y ACTIVAR'}}
function show(x){$('result').textContent=typeof x==='string'?x:JSON.stringify(x,null,2)}
async function saveProvider(){const provider=val('newProvider').trim().toLowerCase();if(!provider){$('providerResult').textContent='Escribe el identificador del proveedor.';return}try{const d=await req('/api/v1/provider-accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,label:val('newLabel'),email:val('email'),api_key:'temporary-session-key',base_url:val('newBase'),auth_location:val('newAuthLocation'),auth_name:val('newAuthName'),test_path:val('newTestPath')})});$('providerResult').textContent='✅ Proveedor registrado. Ahora selecciónalo y conecta su API Key.';await load();}catch(e){$('providerResult').textContent='❌ '+e.message}}
async function activate(id){try{await req('/api/v1/provider-accounts/'+id+'/activate',{method:'POST'});await load()}catch(e){alert(e.message)}}
async function removeProvider(id){if(!confirm('¿Quitar este proveedor de la lista?'))return;try{await req('/api/v1/provider-accounts/'+id,{method:'DELETE'});await load()}catch(e){alert(e.message)}}
async function analyzeAll(){const p=rows.find(x=>x.active);if(!p||p.provider!=='oddspapi'){$('analysisStatus').textContent='Conecta OddsPapi para ejecutar este análisis.';return}$('analysisStatus').textContent='Analizando...';try{const d=await req('/api/v1/oddspapi/scan?deep=true&max_requests=40',{method:'POST'});const s=d.summary||{};$('analysisStatus').textContent='✅ Análisis terminado.';$('reportMetrics').innerHTML=[['Deportes',s.sports],['Eventos 48h',s.fixtures_48h],['Torneos',s.tournaments],['Participantes',s.participants_48h],['Casas',s.bookmakers],['Países',s.countries],['Mercados',s.markets],['Resultados',s.market_outcomes],['LIVE',s.live_fixtures_48h],['PRE',s.upcoming_fixtures_48h]].map(x=>`<div class="metric"><b>${x[1]??0}</b><span>${x[0]}</span></div>`).join('')}catch(e){$('analysisStatus').textContent='❌ '+e.message}}
load();
</script></body></html>'''
    return HTMLResponse(html)
