from __future__ import annotations

from datetime import date
from fastapi.responses import HTMLResponse


def dashboard_html(today: date) -> str:
    return '''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Betano Live Analyzer</title>
<style>body{font-family:Arial,sans-serif;background:#f5f7fb;margin:0;color:#172033}header{background:#101827;color:white;padding:22px 28px}h1{margin:0 0 5px}main{max-width:1400px;margin:25px auto;padding:0 18px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:20px}button{border:0;border-radius:10px;padding:11px 14px;background:white;cursor:pointer;font-weight:700;box-shadow:0 1px 5px #0001}.active{background:#172033;color:white}.card{background:white;border-radius:14px;padding:20px;box-shadow:0 2px 10px #0001;margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.metric b{font-size:25px;display:block;margin-top:6px}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #e7eaf0;text-align:left;font-size:13px}th{background:#f8f9fc}.muted{color:#697386}.notice{padding:12px;border-radius:10px;background:#fff8e6;margin-top:12px}.section-title{display:flex;justify-content:space-between;align-items:center;gap:10px}.strong{font-weight:800}.surebet-buttons{display:flex;gap:10px;flex-wrap:wrap;margin:12px 0}.live-button{background:#8b1e1e;color:white}.status{margin:8px 0;font-size:13px}.profit{font-weight:800}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}table{display:block;overflow-x:auto;white-space:nowrap}}</style></head><body>
<header><h1>⚽ Betano Live Analyzer</h1><div>Radar maestro · Surebet · Selección final · Backtest · CLV · Rendimiento histórico</div></header><main>
<div class="tabs"><button class="tab active" data-period="hoy">HOY</button><button class="tab" data-period="lunes-viernes">LUNES A VIERNES</button><button class="tab" data-period="sabado-domingo">SÁBADO A DOMINGO</button><button class="tab" data-period="mes">MES</button><button class="tab" data-period="3-meses">3 MESES</button><button class="tab" data-period="6-meses">6 MESES</button><button class="tab" data-period="todos">TODOS</button></div>
<div class="card"><div class="section-title"><h2>💰 Surebet</h2></div><div class="surebet-buttons"><button onclick="loadSurebetPre()">📅 SUREBET PRE-PARTIDO</button><button class="live-button" onclick="loadSurebetLive()">🔴 SUREBET EN VIVO · ACTUALIZAR AHORA</button></div><div class="status muted" id="surebet-status">El filtro en vivo NO consulta la API hasta que pulses el botón.</div><div id="surebet" class="muted">Selecciona un filtro para ver oportunidades.</div></div>
<div class="card"><div class="section-title"><h2>🎯 Selección final</h2><button onclick="loadFinal()">Actualizar</button></div><div id="final" class="muted">Cargando...</div></div>
<div class="card"><div class="section-title"><h2>🧠 Radar maestro</h2><button onclick="loadMaster()">Actualizar</button></div><div id="master" class="muted">Cargando...</div></div>
<div class="card"><h2>💰 Mis apuestas</h2><div id="performance" class="grid"></div></div>
<div class="card"><h2>📈 CLV</h2><div id="clv" class="grid"></div></div>
<div class="card"><div class="section-title"><h2>🧪 Backtest: original vs conservador vs real</h2><button onclick="loadBacktest()">Actualizar</button></div><div id="backtest" class="muted">Cargando...</div></div>
<div class="card"><h2>📊 Competición + mercado</h2><div id="groups" class="muted">Cargando...</div></div>
<div class="notice">⚠️ El sistema analiza datos y no garantiza ganancias. El surebet solo se considera arbitraje cuando la suma de probabilidades implícitas de las mejores cuotas es menor que 1. La consulta de cuotas en vivo es manual para evitar gastar consultas innecesariamente.</div>
</main><script>
let currentPeriod='hoy';
document.querySelectorAll('.tab').forEach(x=>x.addEventListener('click',()=>{currentPeriod=x.dataset.period;document.querySelectorAll('.tab').forEach(y=>y.classList.toggle('active',y===x));loadPerformance();loadBacktest();loadCLV();}));
function renderSurebet(d){const rows=d.opportunities||[];if(!rows.length){surebet.innerHTML='<p>No hay surebets disponibles con los datos actuales.</p>';return}surebet.innerHTML='<table><thead><tr><th>Partido</th><th>Mercado</th><th>Línea</th><th>Resultado</th><th>Casa</th><th>Cuota</th><th>Margen</th></tr></thead><tbody>'+rows.flatMap(o=>Object.entries(o.outcomes||{}).map(([selection,q])=>`<tr><td>${o.match}</td><td>${o.market}</td><td>${o.line??'-'}</td><td class="strong">${selection}</td><td>${q.bookmaker}</td><td>${q.odds}</td><td class="profit">${(o.profit_margin*100).toFixed(2)}%</td></tr>`)).join('')+'</tbody></table>'}
async function loadSurebetPre(){surebetStatus.textContent='Consultando las cuotas ya almacenadas; no se hace una consulta live nueva.';const r=await fetch('/api/v1/arbitrage/pre-match?limit=100');const d=await r.json();surebetStatus.textContent=`Filtro PRE-PARTIDO · ${d.opportunities?.length||0} surebets detectadas.`;renderSurebet(d)}
async function loadSurebetLive(){surebetStatus.textContent='🔄 Consultando cuotas EN VIVO ahora...';surebet.innerHTML='<p>Actualizando datos live...</p>';try{const r=await fetch('/api/v1/arbitrage/live?limit=100&hours=1&limit_matches=20',{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Error al consultar live');surebetStatus.textContent=`🔴 Filtro EN VIVO actualizado ahora · ${d.sync.live_matches_seen||0} partidos live consultados · ${d.opportunities?.length||0} surebets.`;renderSurebet(d)}catch(e){surebetStatus.textContent='❌ No se pudo actualizar el radar live: '+e.message;surebet.innerHTML=''}}
async function loadFinal(){const d=await fetch('/api/v1/final-selection?limit=10').then(r=>r.json());const rows=d.opportunities||[];if(!rows.length){final.innerHTML='<p>No hay apuestas que superen los filtros de seguridad actuales.</p>';return}final.innerHTML='<table><thead><tr><th>Partido</th><th>Mercado</th><th>Selección</th><th>Cuota</th><th>Edge</th><th>EV</th><th>Score</th><th>Acción</th></tr></thead><tbody>'+rows.map(o=>`<tr><td>${o.match}</td><td>${o.market}</td><td class="strong">${o.selection}</td><td>${o.odds}</td><td>${(o.edge*100).toFixed(1)}%</td><td>${(o.ev*100).toFixed(1)}%</td><td>${o.master_score}</td><td class="strong">${o.action}</td></tr>`).join('')+'</tbody></table>'}
async function loadMaster(){const d=await fetch('/api/v1/master-radar?limit=15').then(r=>r.json());const rows=d.opportunities||[];if(!rows.length){master.innerHTML='<p>No hay candidatos con datos suficientes.</p>';return}master.innerHTML='<table><thead><tr><th>Partido</th><th>Mercado</th><th>Selección</th><th>Cuota</th><th>Edge</th><th>Consenso</th><th>Movimiento</th><th>CLV</th><th>Score</th><th>Rating</th></tr></thead><tbody>'+rows.map(o=>`<tr><td>${o.match}</td><td>${o.market}</td><td>${o.selection}</td><td>${o.odds}</td><td>${(o.edge*100).toFixed(1)}%</td><td>${o.bookmakers}</td><td>${(o.movement*100).toFixed(1)}%</td><td>${(o.average_clv*100).toFixed(2)}%</td><td class="strong">${o.master_score}</td><td>${o.rating.toUpperCase()}</td></tr>`).join('')+'</tbody></table>'}
async function loadPerformance(){const d=await fetch('/api/v1/bets/summary?period='+currentPeriod).then(r=>r.json());performance.innerHTML=`<div class="metric">Apuestas<b>${d.bets}</b></div><div class="metric">Ganadas<b>${d.wins}</b></div><div class="metric">Perdidas<b>${d.losses}</b></div><div class="metric">Neto<b>S/ ${d.net.toFixed(2)}</b></div><div class="metric">ROI<b>${(d.roi*100).toFixed(2)}%</b></div>`}
async function loadCLV(){const d=await fetch('/api/v1/clv/summary?period='+currentPeriod).then(r=>r.json());clv.innerHTML=`<div class="metric">Snapshots<b>${d.snapshots}</b></div><div class="metric">CLV positivo<b>${d.positive}</b></div><div class="metric">CLV negativo<b>${d.negative}</b></div><div class="metric">Tasa positiva<b>${(d.positive_rate*100).toFixed(1)}%</b></div><div class="metric">CLV medio<b>${(d.average_clv*100).toFixed(2)}%</b></div>`}
async function loadBacktest(){const d=await fetch('/api/v1/backtest/report?period='+currentPeriod).then(r=>r.json());const a=d.overall.original,c=d.overall.conservative,r=d.overall.actual;backtest.innerHTML=`<table><thead><tr><th>Estrategia</th><th>Apuestas</th><th>Aciertos</th><th>Fallos</th><th>Hit rate</th><th>Net</th><th>ROI</th></tr></thead><tbody><tr><td>Original</td><td>${a.bets}</td><td>${a.wins}</td><td>${a.losses}</td><td>${(a.hit_rate*100).toFixed(1)}%</td><td>${a.net_units.toFixed(2)} u</td><td>${(a.roi*100).toFixed(2)}%</td></tr><tr><td>Conservador</td><td>${c.bets}</td><td>${c.wins}</td><td>${c.losses}</td><td>${(c.hit_rate*100).toFixed(1)}%</td><td>${c.net_units.toFixed(2)} u</td><td>${(c.roi*100).toFixed(2)}%</td></tr><tr><td>Real</td><td>${r.bets}</td><td>${r.wins}</td><td>${r.losses}</td><td>${(r.hit_rate*100).toFixed(1)}%</td><td>S/ ${r.net.toFixed(2)}</td><td>${(r.roi*100).toFixed(2)}%</td></tr></tbody></table>`}
async function loadGroups(){const d=await fetch('/api/v1/performance/competition-market').then(r=>r.json());if(!d.groups.length){groups.innerHTML='<p>Aún no hay resultados registrados.</p>';return}groups.innerHTML='<table><thead><tr><th>Competición</th><th>Mercado</th><th>Picks</th><th>Hit rate</th><th>ROI</th><th>Muestra</th></tr></thead><tbody>'+d.groups.map(x=>`<tr><td>${x.competition}</td><td>${x.market}</td><td>${x.picks}</td><td>${(x.hit_rate*100).toFixed(1)}%</td><td>${(x.roi*100).toFixed(2)}%</td><td>${x.sample_status}</td></tr>`).join('')+'</tbody></table>'}
loadFinal();loadMaster();loadPerformance();loadCLV();loadBacktest();loadGroups();</script></body></html>'''


def dashboard_response(today: date) -> HTMLResponse:
    return HTMLResponse(dashboard_html(today))
