from __future__ import annotations

from datetime import date
from fastapi.responses import HTMLResponse


def dashboard_html(today: date) -> str:
    return '''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Betano Live Analyzer</title>
<style>body{font-family:Arial,sans-serif;background:#f5f7fb;margin:0;color:#172033}header{background:#101827;color:white;padding:22px 28px}h1{margin:0 0 5px}main{max-width:1400px;margin:25px auto;padding:0 18px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:20px}button{border:0;border-radius:10px;padding:11px 14px;background:white;cursor:pointer;font-weight:700;box-shadow:0 1px 5px #0001}.active{background:#172033;color:white}.card{background:white;border-radius:14px;padding:20px;box-shadow:0 2px 10px #0001;margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.metric b{font-size:25px;display:block;margin-top:6px}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #e7eaf0;text-align:left;font-size:13px}th{background:#f8f9fc}.muted{color:#697386}.notice{padding:12px;border-radius:10px;background:#fff8e6;margin-top:12px}.section-title{display:flex;justify-content:space-between;align-items:center;gap:10px}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}table{display:block;overflow-x:auto;white-space:nowrap}}</style></head><body>
<header><h1>⚽ Betano Live Analyzer</h1><div>Radar futuro · Backtest · Rendimiento histórico</div></header><main>
<div class="tabs"><button class="tab active" data-period="dia">HOY</button><button class="tab" data-period="lunes-viernes">LUNES A VIERNES</button><button class="tab" data-period="sabado-domingo">SÁBADO A DOMINGO</button><button class="tab" data-period="mes">MES</button><button class="tab" data-period="3-meses">3 MESES</button><button class="tab" data-period="6-meses">6 MESES</button><button class="tab" data-period="todos">TODOS</button></div>
<div class="card"><div class="section-title"><h2>🎯 Radar</h2><button onclick="loadRadar()">Actualizar</button></div><div id="radar" class="muted">Cargando...</div></div>
<div class="card"><h2>💰 Mis apuestas</h2><div id="performance" class="grid"></div></div>
<div class="card"><div class="section-title"><h2>🧪 Backtest: original vs conservador</h2><button onclick="loadBacktest()">Actualizar</button></div><div id="backtest" class="muted">Cargando...</div></div>
<div class="card"><h2>📊 Competición + mercado</h2><div id="groups" class="muted">Cargando...</div></div>
<div class="notice">⚠️ El sistema analiza datos y no garantiza ganancias. Las muestras pequeñas se marcan como insuficientes y no deben tratarse como evidencia sólida.</div>
</main><script>
let currentPeriod='dia';
document.querySelectorAll('.tab').forEach(x=>x.addEventListener('click',()=>{currentPeriod=x.dataset.period;document.querySelectorAll('.tab').forEach(y=>y.classList.toggle('active',y===x));loadPerformance();loadBacktest();}));
async function loadRadar(){const d=await fetch('/api/v1/opportunities?limit=20').then(r=>r.json());if(!d.opportunities.length){radar.innerHTML='<p>No hay oportunidades calificadas con los datos disponibles.</p>';return}radar.innerHTML='<table><thead><tr><th>Competición</th><th>Partido</th><th>Mercado</th><th>Selección</th><th>Cuota</th><th>Prob.</th><th>Edge</th><th>Consenso</th><th>Rating</th></tr></thead><tbody>'+d.opportunities.map(o=>`<tr><td>${o.competition}</td><td>${o.match}<br><span class="muted">${o.kickoff}</span></td><td>${o.market}</td><td>${o.selection}</td><td>${o.odds}</td><td>${(o.model_probability*100).toFixed(1)}%</td><td>${(o.edge*100).toFixed(1)}%</td><td>${o.consensus}</td><td>${o.rating.toUpperCase()}</td></tr>`).join('')+'</tbody></table>'}
async function loadPerformance(){const d=await fetch('/api/v1/bets/summary?period='+currentPeriod).then(r=>r.json());performance.innerHTML=`<div class="metric">Apuestas<b>${d.bets}</b></div><div class="metric">Ganadas<b>${d.wins}</b></div><div class="metric">Perdidas<b>${d.losses}</b></div><div class="metric">Neto<b>S/ ${d.net.toFixed(2)}</b></div><div class="metric">ROI<b>${(d.roi*100).toFixed(2)}%</b></div>`}
async function loadBacktest(){const d=await fetch('/api/v1/backtest/report?period='+currentPeriod).then(r=>r.json());const a=d.overall.original,c=d.overall.conservative;backtest.innerHTML=`<table><thead><tr><th>Estrategia</th><th>Apuestas</th><th>Aciertos</th><th>Fallos</th><th>Hit rate</th><th>Net units</th><th>ROI</th></tr></thead><tbody><tr><td>Original</td><td>${a.bets}</td><td>${a.wins}</td><td>${a.losses}</td><td>${(a.hit_rate*100).toFixed(1)}%</td><td>${a.net_units.toFixed(2)}</td><td>${(a.roi*100).toFixed(2)}%</td></tr><tr><td>Conservador</td><td>${c.bets}</td><td>${c.wins}</td><td>${c.losses}</td><td>${(c.hit_rate*100).toFixed(1)}%</td><td>${c.net_units.toFixed(2)}</td><td>${(c.roi*100).toFixed(2)}%</td></tr></tbody></table>`}
async function loadGroups(){const d=await fetch('/api/v1/performance/competition-market').then(r=>r.json());if(!d.groups.length){groups.innerHTML='<p>Aún no hay resultados registrados.</p>';return}groups.innerHTML='<table><thead><tr><th>Competición</th><th>Mercado</th><th>Picks</th><th>Hit rate</th><th>ROI</th><th>Muestra</th></tr></thead><tbody>'+d.groups.map(x=>`<tr><td>${x.competition}</td><td>${x.market}</td><td>${x.picks}</td><td>${(x.hit_rate*100).toFixed(1)}%</td><td>${(x.roi*100).toFixed(2)}%</td><td>${x.sample_status}</td></tr>`).join('')+'</tbody></table>'}
loadRadar();loadPerformance();loadBacktest();loadGroups();</script></body></html>'''


def dashboard_response(today: date) -> HTMLResponse:
    return HTMLResponse(dashboard_html(today))
